services:
  bibliotech-mysql:
    container_name: bibliotech-db
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: